CREATE USER myuser1 WITH PASSWORD '1';
CREATE USER myuser2 WITH PASSWORD '2';
CREATE DATABASE mydb;

GRANT ALL PRIVILEGES ON DATABASE mydb TO myuser1;
ALTER USER myuser1 WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS;
GRANT CONNECT ON DATABASE mydb TO myuser2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO myuser2;

ALTER USER myuser1 WITH PASSWORD 'pass1';
ALTER USER myuser2 WITH PASSWORD 'pass2';
